In [2]:
import sqlite3
import pandas as pd
import numpy as np

In [18]:
conn = sqlite3.connect('./db/diet_control.db')
df_diet = pd.read_sql_query('SELECT * from diet', conn)

df_diet['Data'] = pd.to_datetime(df_diet['Data'])

df_dates = pd.DataFrame({
    'Data': pd.date_range(
        start=df_diet['Data'].min(),
        end='31/12/2026',
        freq='D'
    )
})

df_dates['Mes_Ano'] = df_dates['Data'].dt.to_period('M')

# df_dates['Data'] = df_diet['Data'].dt.strftime('%d/%m')

dia_atual = pd.Timestamp.today().normalize()
# dia_atual = hoje.to_period('D')
# mes_atual = hoje.to_period('M')

# df_dates['Hoje?'] = np.where(df_dates['Data'].dt.normalize() == dia_atual, 1,0)

# df_filtrado = df_dates[df_dates['Data'].dt.normalize() == dia_atual]

print(dia_atual)
df_dates

2026-03-23 00:00:00

          Data  Mes_Ano
0   2026-03-20  2026-03
1   2026-03-21  2026-03
2   2026-03-22  2026-03
3   2026-03-23  2026-03
4   2026-03-24  2026-03
..         ...      ...
282 2026-12-27  2026-12
283 2026-12-28  2026-12
284 2026-12-29  2026-12
285 2026-12-30  2026-12
286 2026-12-31  2026-12

[287 rows x 2 columns]

In [4]:
conn = sqlite3.connect('./db/macros.db')
df_macros = pd.read_sql_query('SELECT * from macros', conn)

df_macros

,id,alimento,quantidade_g,calorias_kcal,proteínas_g,carboidratos_g
0,1,Banana,1.0,90.0,1.0,23.0
1,2,Maçã,1.0,80.0,0.0,21.0
2,3,Ovo,1.0,70.0,6.0,0.0
3,4,Arroz,100.0,130.0,2.5,28.0
4,5,Macarrão,100.0,155.0,5.0,31.0
5,6,Carne,100.0,250.0,26.0,0.0
6,7,Pão,1.0,135.0,4.0,28.0
7,8,Frango,100.0,165.0,31.0,0.0
8,9,Whey,30.0,200.0,30.0,4.0
9,10,Feijão,100.0,80.0,5.0,14.0
10,11,Barra Cereal,26.0,112.0,2.2,7.8
11,13,Pão Hamburguer,62.5,194.0,5.8,33.0
12,14,MC - Double Cheeseburguer,1.0,780.0,29.0,77.0
13,16,Azeite,10.0,90.0,0.0,0.0
14,17,Aveia,100.0,369.0,12.0,60.0
15,18,Iogurte,125.0,120.0,10.0,10.0
16,19,Pasta de Amendoim,20.0,120.0,5.0,4.0

In [ ]:
alimento = 'Banana'
quantidade = 10

def calculate_macros(alimento, quantidade):

    den = (df_macros[df_macros['alimento'] == alimento]['quantidade_g'].sum())

    cals = (df_macros[df_macros['alimento'] == alimento]['calorias_kcal'].sum())/den * quantidade
    prot = df_macros[df_macros['alimento'] == alimento]['proteínas_g'].sum()/den * quantidade
    carbo = df_macros[df_macros['alimento'] == alimento]['carboidratos_g'].sum()/den * quantidade

    return cals, prot, carbo

900.0
10.0
230.0